version: "3"

services:
    database:
        image: postgres
        restart: always
        env_file:
            - .env
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sleep 10 && pg_isready -U postgres"]
            interval: 10s
            retries: 5

    rest:
        build:
            context: ./rest
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - /etc/letsencrypt/live/ricardothiesenapi.sytes.net:/etc/ssl/certs
        container_name: rest
        restart: unless-stopped

    rest2:
        build:
            context: ./rest
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - /etc/letsencrypt/live/ricardothiesenapi.sytes.net:/etc/ssl/certs
        container_name: rest2
        restart: unless-stopped

    rest3:
        build:
            context: ./rest
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - /etc/letsencrypt/live/ricardothiesenapi.sytes.net:/etc/ssl/certs
        container_name: rest3
        restart: unless-stopped

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "9090:9090"
        volumes:
            - /etc/letsencrypt/live/ricardothiesenapi.sytes.net:/etc/nginx/certs
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - rest
        restart: unless-stopped

volumes:
    pg_data:
