version: "3"

services:
    database:
        image: postgres
        restart: always
        env_file:
            - .env
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sleep 10 && pg_isready -U postgres"]
            interval: 10s
            retries: 5

    rest:
        build:
            context: ./rest
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - ./certbot/conf:/etc/letsencrypt:ro
        container_name: rest
        restart: unless-stopped

    rest2:
        build:
            context: ./rest
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - ./certbot/conf:/etc/letsencrypt:ro
        container_name: rest2
        restart: unless-stopped

    rest3:
        build:
            context: ./rest
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - ./certbot/conf:/etc/letsencrypt:ro
        container_name: rest3
        restart: unless-stopped

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        restart: unless-stopped

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
    pg_data:
